[package]
name = "ars"
version = "0.1.0"
authors = ["adamski234 <adamski234@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
key_base = { path = "./key_base" }
libloading = "0.6"
serde_json = "1"

[workspace]
members = [
    "ars_generator",
    "key_base",
]