#TODO make a release version of key copying
[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["ars_generator"]

[config]
end_task = "keycopy" #This should be a dependency of build task, but I couldn't get it to work

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.keycopy]
script = [
	'''
	mkdir -p keys
	for file in target/debug/libstd_*.so
	do
		ln $file ./keys -s
	done
	'''
]