[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["ars_generator", "yttrium_key_base"]

[config]
end_task = "keycopy" #This should be a dependency of build task, but I couldn't get it to work

[tasks.build]
command = "cargo"
args = ["build", "--no-default-features", "--features=loader"]

[tasks.keycopy]
run_task = [
	{ name = "keycopy-release", condition = { profiles = ["release"] } },
	{ name = "keycopy-development", condition = { profiles = ["development"] } },
]

[tasks.keycopy-release]
script = [
	'''
	mkdir -p keys
	for file in target/release/libyttrium_std_*.so
	do
		ln $file ./keys -f
	done
	'''
]

[tasks.keycopy-development]
script = [
	'''
	mkdir -p keys
	for file in target/debug/libyttrium_std_*.so
	do
		ln $file ./keys -f
	done
	'''
]