#TODO make a release version of key copying
[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["ars_generator"]

[tasks.build]
command = "cargo"
args = ["build"]
run_task = "copykeys"

[tasks.copykeys]
workspace = false
script = [
    '''
    mkdir -p keys
    for file in target/debug/libstd_*.so
    do
    cp $file ./keys
    done
    '''
]