#TODO make a release version of key copying
[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["ars_generator"]

[config]
end_task = "keycopy" #This should be a dependency of build task, but I couldn't get it to work

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.keycopy]
run_task = [
	{ name = "keycopy-release", condition = { profiles = ["release"] } },
	{ name = "keycopy-development", condition = { profiles = ["development"] } },
]

[tasks.keycopy-release]
script = [
	'''
	mkdir -p keys
	for file in target/release/libstd_*.so
	do
		ln $file ./keys -sf
	done
	'''
]

[tasks.keycopy-development]
script = [
	'''
	mkdir -p keys
	for file in target/debug/libstd_*.so
	do
		ln $file ./keys -sf
	done
	'''
]